export const DATA = [
  {
    id: 1,
    units: "36",
    size: "9,000",
    occupancy: "63",
    location: "New Jersey",
    image: "/storages/image1.jpg",
    title: "Everything you need to know about how to buy a Self Storage",
  },
  {
    id: 2,
    units: "49",
    size: "12,700",
    occupancy: "638",
    location: "Morocco",
    image: "/storages/image2.jpg",
    title: "Learn Everything about managing and operating a Self Storage",
  },
  {
    id: 3,
    units: "73",
    size: "37,000",
    occupancy: "15",
    location: "Chicago",
    image: "/storages/image3.jpg",
    title: "Everything you need to know about selling a Self Storage",
  },
  {
    id: 4,
    units: "52",
    size: "54,000",
    occupancy: "271",
    location: "Mexico",
    image: "/image17.png",
    title: "Everything you need to know about how to buy a Self Storage",
  },
  {
    id: 5,
    units: "21",
    size: "22,000",
    occupancy: "143",
    location: "Seoul",
    image: "/image7.png",
    title: "Learn Everything about managing and operating a Self Storage",
  },
  {
    id: 6,
    units: "12",
    size: "13,500",
    occupancy: "25",
    location: "South Korea",
    image: "/image16.png",
    title: "Learn Everything about selling a Self Storage",
  },
  {
    id: 7,
    units: "84",
    size: "48,000",
    occupancy: "13",
    location: "Ghana",
    image: "/image7.png",
    title: "Everything you need to know about how to buy a Self Storage",
  },
  {
    id: 8,
    units: "89",
    size: "12,000",
    occupancy: "63",
    location: "India",
    image: "/storages/image8.jpg",
    title: "Everything you need to know about how to buy a Self Storage",
  },
  {
    id: 9,
    units: "96",
    size: "12,130",
    occupancy: "423",
    location: "Portugal",
    image: "/storages/image9.jpg",
    title: "Heading",
  },
  {
    id: 10,
    units: "124",
    size: "1,040",
    occupancy: "673",
    location: "Nairobi",
    image: "/storages/image10.jpg",
    title: "Heading",
  },
  {
    id: 11,
    units: "478",
    size: "72,000",
    occupancy: "913",
    location: "Cairo",
    image: "/storages/image4.jpg",
    title: "Heading",
  },
  {
    id: 12,
    units: "89",
    size: "12,000",
    occupancy: "63",
    location: "Poland",
    image: "/storages/image7.jpg",
    title: "Heading",
  },
  {
    id: 13,
    units: "89",
    size: "12,000",
    occupancy: "63",
    location: "Angola",
  },
  {
    id: 2,
    units: "49",
    size: "12,700",
    occupancy: "638",
    location: "Morocco",
    image: "/storages/image2.jpg",
    title: "Heading",
  },
  {
    id: 3,
    units: "73",
    size: "37,000",
    occupancy: "15",
    location: "Chicago",
    image: "/storages/image3.jpg",
    title: "Heading",
  },
  {
    id: 6,
    units: "12",
    size: "13,500",
    occupancy: "25",
    location: "South Korea",
    image: "/storages/image6.jpg",
    title: "Heading",
  },
  {
    id: 7,
    units: "84",
    size: "48,000",
    occupancy: "13",
    location: "Ghana",
    image: "/storages/image7.jpg",
    title: "Heading",
  },
  {
    id: 10,
    units: "124",
    size: "1,040",
    occupancy: "673",
    location: "Nairobi",
    image: "/storages/image10.jpg",
    title: "Heading",
  },
  {
    id: 11,
    units: "478",
    size: "72,000",
    occupancy: "913",
    location: "Cairo",
    image: "/storages/image4.jpg",
    title: "Heading",
  },
];
